project = "sqla-pollux"
copyright = "2026, Daniel Popowich"
author = "Daniel Popowich"
extensions = ["myst_parser", "sphinx.ext.autodoc", "sphinx.ext.viewcode"]
myst_enable_extensions = ["colon_fence", "deflist"]
templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]
html_theme = "sphinx_rtd_theme"
html_theme_options = {"logo_only": False, "display_version": True}
myst_heading_anchors = 3